# Generated by Django 5.2.1 on 2025-06-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.URLField()),
                ('conteudo', models.TextField()),
                ('documento', models.FileField(upload_to='documentos')),
            ],
        ),
    ]
